[2022-07-04 16:06:47,267] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.is_api_available manual__2022-07-04T16:06:44.457684+00:00 [queued]>
[2022-07-04 16:06:47,277] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.is_api_available manual__2022-07-04T16:06:44.457684+00:00 [queued]>
[2022-07-04 16:06:47,277] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 16:06:47,277] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-04 16:06:47,277] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 16:06:47,292] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-04 16:06:44.457684+00:00
[2022-07-04 16:06:47,296] {standard_task_runner.py:52} INFO - Started process 1067 to run task
[2022-07-04 16:06:47,301] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'is_api_available', 'manual__2022-07-04T16:06:44.457684+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpr8jqpw1s', '--error-file', '/tmp/tmp6f2a0ah5']
[2022-07-04 16:06:47,301] {standard_task_runner.py:80} INFO - Job 27: Subtask is_api_available
[2022-07-04 16:06:47,358] {task_command.py:370} INFO - Running <TaskInstance: first_dag.is_api_available manual__2022-07-04T16:06:44.457684+00:00 [running]> on host b631230cc7b5
[2022-07-04 16:06:47,434] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T16:06:44.457684+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T16:06:44.457684+00:00
[2022-07-04 16:06:47,435] {http.py:97} INFO - Poking: api/
[2022-07-04 16:06:47,444] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-04 16:06:47,446] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-04 16:06:47,521] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-04 16:06:47,535] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=is_api_available, execution_date=20220704T160644, start_date=20220704T160647, end_date=20220704T160647
[2022-07-04 16:06:47,556] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 16:06:47,618] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
