[2022-07-04 10:01:28,801] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-04T09:49:59.473162+00:00 [queued]>
[2022-07-04 10:01:28,822] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-04T09:49:59.473162+00:00 [queued]>
[2022-07-04 10:01:28,823] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 10:01:28,823] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2022-07-04 10:01:28,823] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 10:01:28,858] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-07-04 09:49:59.473162+00:00
[2022-07-04 10:01:28,869] {standard_task_runner.py:52} INFO - Started process 961 to run task
[2022-07-04 10:01:28,883] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2022-07-04T09:49:59.473162+00:00', '--job-id', '16', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp9bb4gnly', '--error-file', '/tmp/tmpe_e_eis8']
[2022-07-04 10:01:28,883] {standard_task_runner.py:80} INFO - Job 16: Subtask run_after_loop
[2022-07-04 10:01:29,006] {task_command.py:370} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2022-07-04T09:49:59.473162+00:00 [running]> on host b631230cc7b5
[2022-07-04 10:01:29,138] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T09:49:59.473162+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T09:49:59.473162+00:00
[2022-07-04 10:01:29,140] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-04 10:01:29,142] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-07-04 10:01:29,167] {subprocess.py:85} INFO - Output:
[2022-07-04 10:01:29,171] {subprocess.py:92} INFO - 1
[2022-07-04 10:01:29,174] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-04 10:01:29,228] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220704T094959, start_date=20220704T100128, end_date=20220704T100129
[2022-07-04 10:01:29,275] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 10:01:29,384] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
