[2022-07-04 15:53:49,726] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.is_api_available scheduled__2022-07-03T00:00:00+00:00 [queued]>
[2022-07-04 15:53:49,757] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.is_api_available scheduled__2022-07-03T00:00:00+00:00 [queued]>
[2022-07-04 15:53:49,757] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 15:53:49,757] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-04 15:53:49,758] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 15:53:49,781] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-03 00:00:00+00:00
[2022-07-04 15:53:49,785] {standard_task_runner.py:52} INFO - Started process 418 to run task
[2022-07-04 15:53:49,791] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'is_api_available', 'scheduled__2022-07-03T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpoelaw06v', '--error-file', '/tmp/tmpwfqmjhk1']
[2022-07-04 15:53:49,792] {standard_task_runner.py:80} INFO - Job 22: Subtask is_api_available
[2022-07-04 15:53:49,871] {task_command.py:370} INFO - Running <TaskInstance: first_dag.is_api_available scheduled__2022-07-03T00:00:00+00:00 [running]> on host b631230cc7b5
[2022-07-04 15:53:49,955] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-03T00:00:00+00:00
[2022-07-04 15:53:49,956] {http.py:97} INFO - Poking: api/
[2022-07-04 15:53:49,965] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-04 15:53:49,966] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-04 15:53:50,206] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-04 15:53:50,224] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=is_api_available, execution_date=20220703T000000, start_date=20220704T155349, end_date=20220704T155350
[2022-07-04 15:53:50,242] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 15:53:50,276] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
