[2022-07-04 16:07:51,875] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.store_user manual__2022-07-04T16:06:44.457684+00:00 [queued]>
[2022-07-04 16:07:51,892] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.store_user manual__2022-07-04T16:06:44.457684+00:00 [queued]>
[2022-07-04 16:07:51,892] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 16:07:51,892] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-07-04 16:07:51,892] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 16:07:51,917] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-07-04 16:06:44.457684+00:00
[2022-07-04 16:07:51,922] {standard_task_runner.py:52} INFO - Started process 1135 to run task
[2022-07-04 16:07:51,933] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'store_user', 'manual__2022-07-04T16:06:44.457684+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmphguzpupk', '--error-file', '/tmp/tmpw0x1ynmm']
[2022-07-04 16:07:51,935] {standard_task_runner.py:80} INFO - Job 31: Subtask store_user
[2022-07-04 16:07:52,088] {task_command.py:370} INFO - Running <TaskInstance: first_dag.store_user manual__2022-07-04T16:06:44.457684+00:00 [running]> on host b631230cc7b5
[2022-07-04 16:07:52,271] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T16:06:44.457684+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T16:06:44.457684+00:00
[2022-07-04 16:07:52,274] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-07-04 16:07:52,299] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-04 16:07:52,323] {python.py:173} INFO - Done. Returned value was: None
[2022-07-04 16:07:52,361] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=store_user, execution_date=20220704T160644, start_date=20220704T160751, end_date=20220704T160752
[2022-07-04 16:07:52,390] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-04 16:07:52,476] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
